In [1]:
!ls data

analysis_agg_20200403-135718_code_kl_last.html
analysis_agg_20200403-141520_code_kl_last.html
analysis_agg_20200417-151616_code_kl_last.html
analysis_ts_20200403-135718_code_kl.html
analysis_ts_20200403-135718_human_kl_dissim.html
analysis_ts_20200403-135718_human_kl_var.html
analysis_ts_20200403-141520_code_kl.html
analysis_ts_20200403-141520_human_kl_dissim.html
analysis_ts_20200403-141520_human_kl_var.html
analysis_ts_20200417-151616_code_kl.html
analysis_ts_20200417-151616_human_kl_dissim.html
analysis_ts_20200417-151616_human_kl_var.html
basic_ml_agg_20200403-135718.csv
basic_ml_agg_20200403-141520.csv
basic_ml_agg_20200417-151616.csv
basic_ml_ts_20200403-135718.csv
basic_ml_ts_20200403-141520.csv
basic_ml_ts_20200417-151616.csv
ext_ml_agg_20200417-142015.csv
ext_ml_ts_20200417-142015.csv
r2_agg_20200917-101119.csv
r2_ts_20200917-101119.csv

In [2]:
import pandas as pd

In [3]:
agg = pd.read_csv("data/r2_agg_20200917-101119.csv")
agg.head()

,config,m,n,j,p_1,p_2,p_3,q_h1,q_h2,q_ml,...,human_kl_max,human_kl_last,human_kl_var_max,human_kl_var_last,code_kl_std,human_kl_std,human_kl_dissim_max,human_kl_dissim_last,data_qual_max,data_qual_last
0,1,30,60,15,0.1,0.1,0.1,0.1,0.5,0.5,...,0.6283,0.6283,0.0091,0.0080,NaN,NaN,0.6665,0.4182,0.8000,0.3333
1,2,30,60,15,0.1,0.1,0.1,0.1,0.5,0.5,...,0.5322,0.5111,0.0097,0.0075,NaN,NaN,0.6676,0.3957,0.8667,0.5333
2,3,30,60,15,0.1,0.1,0.1,0.1,0.5,0.5,...,0.6394,0.6350,0.0083,0.0069,NaN,NaN,0.6690,0.4132,0.6667,0.4000
3,4,30,60,15,0.1,0.1,0.1,0.1,0.5,0.5,...,0.5622,0.4633,0.0100,0.0048,NaN,NaN,0.6661,0.4117,0.7333,0.5333
4,5,30,60,15,0.1,0.1,0.1,0.1,0.5,0.5,...,0.6267,0.6267,0.0097,0.0064,NaN,NaN,0.6681,0.3976,0.7667,0.7000

In [4]:
agg.describe()

,config,m,n,j,p_1,p_2,p_3,q_h1,q_h2,q_ml,...,human_kl_max,human_kl_last,human_kl_var_max,human_kl_var_last,code_kl_std,human_kl_std,human_kl_dissim_max,human_kl_dissim_last,data_qual_max,data_qual_last
count,256.000000,256.0,256.0,256.0,256.000000,256.000000,256.000000,2.560000e+02,256.0,256.000000,...,256.000000,256.000000,256.000000,256.000000,0.0,0.0,256.000000,256.000000,256.000000,256.000000
mean,128.500000,30.0,60.0,15.0,0.500000,0.500000,0.500000,1.000000e-01,0.5,0.700000,...,0.669470,0.615574,0.009040,0.004654,NaN,NaN,0.666831,0.279989,0.894013,0.733592
std,74.045031,0.0,0.0,0.0,0.400784,0.400784,0.400784,1.390497e-17,0.0,0.200392,...,0.097573,0.113128,0.001652,0.002643,NaN,NaN,0.002069,0.152126,0.112095,0.189046
min,1.000000,30.0,60.0,15.0,0.100000,0.100000,0.100000,1.000000e-01,0.5,0.500000,...,0.514400,0.370000,0.004900,0.001000,NaN,NaN,0.660100,0.076600,0.666700,0.233300
25%,64.750000,30.0,60.0,15.0,0.100000,0.100000,0.100000,1.000000e-01,0.5,0.500000,...,0.592800,0.534000,0.007900,0.002000,NaN,NaN,0.665400,0.122300,0.791675,0.566700
50%,128.500000,30.0,60.0,15.0,0.500000,0.500000,0.500000,1.000000e-01,0.5,0.700000,...,0.654400,0.610000,0.009200,0.004200,NaN,NaN,0.666900,0.308950,0.966700,0.733300
75%,192.250000,30.0,60.0,15.0,0.900000,0.900000,0.900000,1.000000e-01,0.5,0.900000,...,0.714450,0.668450,0.010100,0.007000,NaN,NaN,0.668300,0.430525,1.000000,0.900000
max,256.000000,30.0,60.0,15.0,0.900000,0.900000,0.900000,1.000000e-01,0.5,0.900000,...,0.952800,0.947200,0.013500,0.010500,NaN,NaN,0.672100,0.475000,1.000000,1.000000